### ISSUE TITLE
Steady sine tone - after playing/rendering

### ISSUE THREAD

**Issue by csounder** [csound/web-ide#102] opened 2020-07-22 14:35 UTC
When I click on a featured example to play - such as Thorin Kerr's - Blue and then... stop playing, what emerges is a content tone (like a final buffer that is looping).  This happens when I stop playing any example.

**Comment by kunstmusik** [comment] 2020-07-25 19:40
I was able to reproduce this on Chrome but not on other browsers. Interestingly, it seems to be an issue on Chrome 84 (the latest stable release), but not on Chrome 86 (the latest Canary dev release). I wonder if a bug was introduced in Chrome 84 that was later fixed?  We'll have to check the Chrome bug tracker to find out.

**Comment by kunstmusik** [comment] 2020-07-25 19:48
Following up, we found that this was a bug specifically in Chrome 84. This was reported and triaged in the Chromium bug tracker:

https://bugs.chromium.org/p/chromium/issues/detail?id=1106973&q=audioworklet&can=2
https://bugs.chromium.org/p/chromium/issues/detail?id=1099756

The bug reports mention that it is fixed in Chrome 85. I saw another report of a problem on the WebAudio Slack, also with 84, so it is a Chrome problem.  We can't really fix the issue since it's in the system, but we might be able to put up a dialog for the short term to report to the user that Chrome 84 has a bug and to use another browser.

**Comment by csounder** [comment] 2020-07-26 02:05
It ran clean on Catalina yesterday.  No tone.  Might be fixed now?  Hope so

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by kunstmusik** [comment] 2020-08-26 03:25
I see that Chrome 85 is now out. I tested there and it seems to no longer have the problem. Closing out this issue with the resolution that if you have Chrome 84 that you should update to Chrome 85.

**Closed by kunstmusik** 2020-08-26 03:25 UTC
